
[[action]]
type="check_installed"
name="xelatex"

[[action]]
type="ensure_cache"
file="awesome-cv.cls"
source="github"
meta="posquit0/Awesome-CV/master/awesome-cv.cls"

[[action]]
type="run_pandoc"
output="output.tex"
template="$preset$/awesome.tex"
outputType="latex"

[[action]]
type="run_xelatex"
input="output.tex"
includeDirs=["$cache$"]
