name: Publish Release on Manifest Change

on:
  push:
    paths:
      - 'manifest.json'
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install zip
      run: sudo apt-get install zip

    - name: Read manifest.json
      id: read_manifest
      run: |
        # First check if name contains localization markers
        raw_name=$(jq -r '.name' manifest.json)
        if [[ "$raw_name" == *"{{"* ]]; then
          # If name is localized, get it from _locales/en.json
          manifest_name=$(jq -r '.manifest.app.name' _locales/en.json)
          echo "Using localized name from _locales/en.json"
        else
          # Otherwise use the raw name from manifest.json
          manifest_name=$raw_name
        fi
        # Get version as before
        manifest_version=$(jq -r '.version' manifest.json)
        # Set environment variables
        echo "MANIFEST_NAME=$manifest_name" >> $GITHUB_ENV
        echo "MANIFEST_VERSION=$manifest_version" >> $GITHUB_ENV

    - name: Check if release exists
      id: check_release
      run: |
        release_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ env.MANIFEST_VERSION }}" | jq -r '.id')
        if [ "$release_id" != "null" ]; then
          echo "Release already exists. Exiting."
          exit 0
        fi

    - name: Create Production manifest
      run: |
        cp manifest.json manifest.prod.json
        jq '.devTools = false' manifest.prod.json > manifest.temp.json && mv manifest.temp.json manifest.prod.json

    - name: Create Debug manifest
      run: |
        cp manifest.json manifest.debug.json
        jq '.devTools = true' manifest.debug.json > manifest.temp.json && mv manifest.temp.json manifest.debug.json

    - name: Zip files
      run: |
        # Production zip
        zip -r "${{ env.MANIFEST_NAME }}.eagleplugin" * \
            -x ".*" -x ".*/**" -x "docs/*" -x "docs-asset/*" -x "manifest.json" \
            -x "manifest.debug.json" -x "*.eagleplugin"
        mv manifest.prod.json manifest.json
        zip -u "${{ env.MANIFEST_NAME }}.eagleplugin" manifest.json

        # Debug zip
        zip -r "${{ env.MANIFEST_NAME }}-debug.eagleplugin" * \
            -x ".*" -x ".*/**" -x "docs/*" -x "docs-asset/*" -x "manifest.json" \
            -x "manifest.prod.json" -x "*.eagleplugin"
        mv manifest.debug.json manifest.json
        zip -u "${{ env.MANIFEST_NAME }}-debug.eagleplugin" manifest.json

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.MANIFEST_VERSION }}"
        release_name: "v${{ env.MANIFEST_VERSION }}"
        draft: false
        prerelease: false

    - name: Upload Production Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.MANIFEST_NAME }}.eagleplugin
        asset_name: ${{ env.MANIFEST_NAME }}.eagleplugin
        asset_content_type: application/zip

    - name: Upload Debug Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.MANIFEST_NAME }}-debug.eagleplugin
        asset_name: ${{ env.MANIFEST_NAME }}-debug.eagleplugin
        asset_content_type: application/zip