name: update release

on:
  workflow_dispatch:
  push:
    paths:
      - 'pyproject.toml'
      - 'eaglewrap-runner-example/eagleWrapUtils.js'

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read pyproject.toml version
        id: version
        run: |
          VERSION=$(grep -m1 'version = ' pyproject.toml | cut -d'"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if utils changed
        id: changed
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q "eaglewrap-runner-example/eagleWrapUtils.js" && echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false" >> $GITHUB_OUTPUT

      - name: Create or Update Release
        if: steps.changed.outputs.changed == 'true' || !startsWith(github.ref, 'refs/tags/v${{ steps.version.outputs.version }}')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          files: |
            eaglewrap-runner-example/eagleWrapUtils.js
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
