name: Update Template Files

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure required directories exist
        run: |
          mkdir -p .github/workflows
          mkdir -p .github/scripts
          mkdir -p .github/configs
          echo "Created required directories"

      - name: Read template configuration
        id: template-config
        run: |
          TEMPLATE_CONFIG=$(cat .github/configs/templateTarget.json)
          echo "source=$(echo $TEMPLATE_CONFIG | jq -r '.source')" >> $GITHUB_OUTPUT
          echo "branch=$(echo $TEMPLATE_CONFIG | jq -r '.branch')" >> $GITHUB_OUTPUT

      - name: Clone template repository
        run: |
          git clone --depth 1 --branch ${{ steps.template-config.outputs.branch }} ${{ steps.template-config.outputs.source }} template-repo

      - name: Update workflow files
        run: |
          # Protected files that should never be overwritten
          PROTECTED_FILES=("update-gitops.yml")
          
          # Copy all workflow files from template
          if [ -d "template-repo/.github/workflows" ]; then
            for file in template-repo/.github/workflows/*; do
              if [ -f "$file" ]; then
                filename=$(basename "$file")
                # Skip if file is protected
                if [[ " ${PROTECTED_FILES[@]} " =~ " ${filename} " ]]; then
                  echo "Skipping protected workflow: $filename"
                  continue
                fi
                echo "Copying workflow: $filename"
                cp "$file" ".github/workflows/$filename"
              fi
            done
          fi

      - name: Update script files
        run: |
          # Copy all script files from template
          if [ -d "template-repo/.github/scripts" ]; then
            for file in template-repo/.github/scripts/*; do
              if [ -f "$file" ]; then
                filename=$(basename "$file")
                echo "Copying script: $filename"
                cp "$file" ".github/scripts/$filename"
              fi
            done
          fi

      - name: Check for changes
        id: git-check
        run: |
          echo "=== Git Status Before Staging ==="
          git status
          
          # Don't stage protected files
          git add .github/workflows/*.yml 2>/dev/null || true
          git reset .github/workflows/update-template.yml .github/workflows/update-gitops.yml 2>/dev/null || true
          git add .github/scripts/ 2>/dev/null || true
          
          echo "=== Git Status After Staging ==="
          git status
          
          echo "=== Staged Changes ==="
          git diff --staged --name-only
          
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: update template files from source repository"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git push 